Node-develop: create routes for working with notes
petrovskya/lab-node-js pull request #2
Opened 2023-07-06 09:45 UTC by petrovskya

1. Overview: Created routes for working with notes. Notes can be created/edited/deleted/viewed, corresponding to the following request methods POST/PUT/DELETE/GET.

2. Changes:

   Task 2.
     - Created the following routes:
     
           GET - /api/notes - returns an empty array.
           POST - /api/notes - returns the note object sent in the request.
           PUT - /api/notes/:id - returns the note object sent in the request.
           DELETE - /api/notes/:id - returns {success: true, id: " value :id " }.
           
        The note contains several fields:
        
            { id - identifier - required field when editing
              title - note title - required field, at least 3 characters long
              content - note content - required field, at least 3 characters long and no longer than 500 characters
              createdAt - date of note creation
              updatedAt - date of note update, can be empty
             }

     - Used the Render platform to demonstrate the result.
     - Prepared Postman requests in the collection.

3. How to test:
[View Demo](https://lab-node-js.onrender.com/api/notes)
[View Demo. Postman Collection](https://elements.getpostman.com/redirect?entityId=28216450-6be95032-8c27-42ee-8ab6-816975faee07&entityType=collection)

2023-07-06 13:04 UTC, irina-sinitsyna requested changes

2023-07-06 13:04 UTC, irina-komissarova commented on src/api/notes/notes.service.ts
> +    return createNoteDto;
please add entities folder inside /notes and add schema for Note 
https://docs.nestjs.com/techniques/mongodb

2023-07-06 13:04 UTC, irina-komissarova commented on src/api/notes/notes.service.ts
> +    return createNoteDto;
and then use this.subscriptionModel.create

2023-07-06 13:04 UTC, irina-komissarova commented on src/api/notes/notes.service.ts
> +    return updateNoteDto;
same
use models

2023-07-06 13:04 UTC, irina-sinitsyna commented on src/api/notes/notes.service.ts
> +  }
you should get note by id, then check if it's not deleted (add error for this case) and then delete note
try to use soft delete (when note is not deleted, but field isDeleted and deletedAt fields added)

2023-07-18 11:46 UTC, irina-sinitsyna requested changes

2023-07-18 11:46 UTC, irina-sinitsyna commented on src/api/notes/dto/notes.dto.ts
> +  @Transform(({ value }: TransformFnParams) => parseInt(value, 10))
please add a separate util for it and reuse here (also remember about magic numbers)

2023-07-18 11:46 UTC, irina-sinitsyna commented on src/api/notes/notes.service.ts
> +      ...(title && { title: new RegExp(escapeRegExp(title), 'i') }),
it's better to create a consant for regexp value, f.e const titleRegexp = new RegExp(escapeRegExp(title), 'i');

2023-07-18 11:46 UTC, irina-sinitsyna commented on src/api/notes/notes.service.ts
> +      return updatedNote;
please check formatting, there should be an empty line before return statement

2023-07-18 11:46 UTC, irina-sinitsyna commented on src/config/constants/errors.ts
> +  NOTE_TITLE: 'Title should be should be of minimum 3 characters length.',
please check error message, it looks like text duplicating

2023-07-18 11:46 UTC, irina-sinitsyna commented on src/utils/getEndOfTheDay.ts
> +
try to use dayjs lib instead, i guess it will be easier

2023-07-20 10:39 UTC, petrovskya commented on src/utils/getEndOfTheDay.ts
> +
I haven't found a solution with dayjs, that would make work with these constants easier.

2023-07-20 12:27 UTC, irina-sinitsyna commented on src/api/notes/notes.controller.ts
> +import { AccessTokenGuard } from 'guards';
!

2023-07-20 12:46 UTC, irina-sinitsyna commented on src/auth/auth.service.ts
> +    console.log(userId);
!

2023-07-24 07:27 UTC, irina-sinitsyna approved these changes

2023-07-24 07:27 UTC, merged